import { TransitionLink, TransitionGSAP } from "@/components/gsap/Transition";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="box text-black w-screen h-screen">
      <div
        id="transition-element"
        className="w-screen h-screen bg-black -z-10 fixed top-0 left-0"
      />
      <div className="mb-32 grid text-center lg:mb-0 lg:w-full lg:max-w-5xl lg:grid-cols-4 lg:text-left">
        <TransitionLink href="/gsap/page1" label="Page 1" />
        <TransitionLink href="/gsap/page2" label="Page 2" />
        <TransitionLink href="/gsap/page3" label="Page 3" />
      </div>
      <TransitionGSAP>{children}</TransitionGSAP>
    </div>
  );
}
